feed/urls.py
from django.urls import path
from .views import HomePageView
from .views import PostDetailView
from .views import PostView

app_name = "feed"

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('detail/<int:pk>', PostDetailView.as_view(), name='detail'),
    path('post/', PostView.as_view(), name="post"),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

from feed import urls as feed_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(feed_urls, namespace='feed'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from sorl.thumbnail import ImageField
from django.conf import settings

class Post(models.Model):
    text = models.CharField(max_length=140, blank=False, null=False)
    image = ImageField()

    @property
    def img_path(self):
        return f"./media/{self.image.name}"

    def __str__(self):
        return self.text

feed/views.py
from django.views.generic import FormView
from django.views.generic import DetailView
from django.views.generic import TemplateView
from django.contrib import messages
from .models import Post
from .form import PostForm

class HomePageView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.all().order_by('-id')
        return context
    
class PostDetailView(DetailView):
    template_name="details.html"
    model = Post

class PostView(FormView):
    template_name="add_image.html"
    form_class=PostForm
    success_url='/'

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        new_object = Post.objects.create(
            text = form.cleaned_data['text'],
            image = form.cleaned_data['image']
        )

        messages.add_message(self.request, messages.SUCCESS, "POST WAS ADDED SUCCESSFULLY")

        return super().form_valid(form)

templates/add_image.html
{% extends 'base.html' %}


{% block title %}Image Share | Add New Image{% endblock %}

{% block body %}
    <div class="row justify-content-md-center my-5">
        <div class="col-2">
            <h2 class="text-center">Add Image</h2>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="d-grid gap-2">
                    <button class="btn btn-success btn-lg" type="submit">SUBMIT</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}
    
    

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>{% block title %}Image Share{% endblock %}</title>
</head>
<body>
    {% include 'includes/navbar.html' %}

    {% if messages %}
        {% for message in messages %}
            <p{% if message.tags %} class="bg-{{ message.tags }} bg-gradient py-4 text-center text-white"{% endif %}>{{ message }}</p>
        {% endfor %}
    {% endif %}
    
    {% block body %}
    {% endblock %}
        
</body>
</html>

templates/details.html
{% extends 'base.html' %}

{% block title %}Image Share | Details View{% endblock %}


{% block body %}
    <div class="row justify-content-md-center">
        <div class="col-6">
            <h1>Description:</h1>
            <p style="font-size: 25px; color: teal;"><b>{{ post.text }}</b></p>
            <h1>Image:</h1>
            <img src={{ post.image.url }} class="img-fluid rounded" alt="" style="width: 100%; height: auto;">
        </div>
    </div>
{% endblock %}
    

templates/home.html
{% extends 'base.html' %}
{% load sorl_thumbnail %}

{% block title %}Image Share | Home Page{% endblock %}
    

{% block body %}
    <div class="container text-center">
        <div class="row">
            {% for post in posts %}
                <div class="card my-5 col-6 col-sm-3" style="width: 18rem; margin-right: 15px;">
                    {% thumbnail post.image "200x200" crop="center" as im %}
                        <img src="{{ im.url }}" class="card-img-top">
                    {% endthumbnail %}
                    <div class="card-body">
                    <p class="card-text">{{ post.text }}</p>
                    <a href="{% url 'feed:detail' post.id %}" class="btn btn-primary">Details</a>
                    </div>
                </div>
            {% empty %}
                <hr>
                <div class="text-center my-5">
                    <h2>Welcome Do You Want to Add Yout First Image?</h2>
                </div>
                <div class="row justify-content-md-center my-5">
                    <div class="col-2">
                        <form action="" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="d-grid gap-2">
                                <a class="btn btn-success btn-lg" href="post/">Add Image</a>
                            </div>
                        </form>
                    </div>
                </div>
                <hr>
            {% endfor %}
        </div>
    </div> 
{% endblock %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Image Share</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="post/">Add Image</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>